Add section on how to add the initial user in Quarkus distribution.
keycloak/keycloak-web pull request #284
Opened 2022-03-02 10:24 UTC by ahus1

Also fixing a link and formatting.

Closes #283

2022-03-02 12:29 UTC, jonkoops requested changes

2022-03-02 12:29 UTC, jonkoops commented on guides/migration/migrating-to-quarkus.adoc
> +The Keycloak Wildfly distribution contained scripts like `add-user-keycloak.sh` to add initial users to keycloak.
```suggestion
The Keycloak Wildfly distribution contained scripts named `add-user-keycloak.sh` to add initial users to Keycloak.
```

2022-03-02 12:29 UTC, jonkoops commented on guides/migration/migrating-to-quarkus.adoc
> +To add the initial admin user, set the environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` for username and password of the user.
```suggestion
To add the initial admin user, set the environment variables `KEYCLOAK_ADMIN` and `KEYCLOAK_ADMIN_PASSWORD` for the username and password of the user.
```

2022-03-02 12:49 UTC, ahus1 commented
@jonkoops - thanks, accepted your changed and squashed them. Please re-review to approve.

2022-03-02 13:07 UTC, jonkoops approved these changes
LGTM

2022-03-11 09:24 UTC, stianst approved these changes

2022-03-11 09:24 UTC, merged