Preview - Keycloak Test Framework
keycloak/keycloak-web pull request #488
Opened 2024-08-29 14:31 UTC by lhanusov

Closes #32399

2024-08-29 20:33 UTC, vaceksimon requested changes
Content-wise I don't find it missing anything. It's great as it is now.
I ran it through a grammar checker and included some of my rephrasing suggestions.
Feel free to ignore any of it.

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +Keycloak team had started a https://github.com/orgs/keycloak/projects/42[joint effort] between the engineering and quality engineering people to design a new https://github.com/keycloak/keycloak/tree
```suggestion
Keycloak team had started a https://github.com/orgs/keycloak/projects/42[joint effort] between the engineering and quality engineering people to design a new test framework (May 2024). It had been initiated with a prototype to verify if our thoughts were feasible. The prototype was based on the _JUnit5_ testing framework, specifically to implement _JUnit5_ callback classes which extend the default test lifecycle functionality and provide custom inject annotations, like _@KeycloakIntegrationTest_, _@InjectWebDriver_ or _@InjectRealm_.
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +For our purpose we've https://github.com/keycloak/keycloak/blob/main/test-framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTestExtension.java[implemented] these three callback c
```suggestion
For our purpose, we have https://github.com/keycloak/keycloak/blob/main/test-framework/src/main/java/org/keycloak/test/framework/KeycloakIntegrationTestExtension.java[implemented] these three callback classes:
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +Are you curious where to start?
```suggestion
== Are you curious about where to start?
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +We suggest to read the https://github.com/keycloak/keycloak/blob/main/test-framework/README.md[user guide], which will provide a basic overview how the framework works and should be used. If this is
```suggestion
We suggest reading the https://github.com/keycloak/keycloak/blob/main/test-framework/README.md[user guide], which will provide a basic overview of how the framework works and should be used. If this is not enough, you can also check https://github.com/keycloak/keycloak/tree/main/test-poc/examples[examples module].
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +Once you find some bug or want to discuss something, or propose a new enhancement, please follow this GitHub feedback https://www.github.com/discussion#blabla[discussion] link.
```suggestion
Once you find a bug, want to discuss something, or propose a new enhancement, please follow this GitHub feedback https://www.github.com/discussion#blabla[discussion] link.
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +Preview - https://github.com/keycloak/keycloak/tree/main/test-framework[_Keycloak Test Framework_] will be introduced in _Keycloak 26_. We plan to add more features, which will cover 80% of functiona
```suggestion
Preview - https://github.com/keycloak/keycloak/tree/main/test-framework[_Keycloak Test Framework_] will be introduced in _Keycloak 26_. We plan to add more features, which will cover 80% of functionalities currently available in the https://github.com/keycloak/keycloak/tree/main/testsuite[integration test suite]. We also plan to introduce some new concepts, e.g. _@KeycloakTest_ annotation, which will add an option to test providers without the _Keycloak_ server running. It should be based on the _KeycloakSession_ class. Other interesting features should be parallel execution on a GitHub runner, adding a custom extension to a Keycloak server, or enabling a Keycloak cluster setup.
```

2024-08-29 20:33 UTC, vaceksimon commented on blog/2024/preview-keycloak-test-framework.adoc
> +I would like to thanks to all people who put the proof of concept together and made it a real: Miquel, Simon, Filip, Moises, Jon, Pedro. Special thanks goes to Stian, who led the technical design and
```suggestion
I would like to thank all the people who put the proof of concept together and made it real: Miquel, Simon, Filip, Moises, Jon, and Pedro. A special thank you goes to Stian, who led the technical design and proposed very nifty things that raised the project to another level.
```

2024-09-02 10:25 UTC, vaceksimon approved these changes

2024-09-27 09:11 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +For extension developers we recommend to look into the showcase example on how to start _Keycloak_ with their custom provider - link.
Just a note that we need to update this before publishing the blog

2024-09-27 09:11 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Once you find a bug, want to discuss something, or propose a new enhancement, please follow this GitHub feedback https://www.github.com/discussion#blabla[discussion] link.
Just a note that we need to update this before publishing the blog

2024-09-27 09:12 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Preview - https://github.com/keycloak/keycloak/tree/main/test-framework[_Keycloak Test Framework_] will be introduced in _Keycloak Nightly_ builds. We plan to add more features, which will cover 80%
Is available, not will be ;)

2024-09-27 09:12 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Preview - https://github.com/keycloak/keycloak/tree/main/test-framework[_Keycloak Test Framework_] will be introduced in _Keycloak Nightly_ builds. We plan to add more features, which will cover 80%
Remove 80%, and say something like cover enough for most tests...

2024-09-27 09:13 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Keycloak team had started a https://github.com/orgs/keycloak/projects/42[joint effort] between the engineering and quality engineering people to design a new test framework (May 2024). It had been in
The board is private, and not visible to everyone. So we either remove the link, or cleanup the board and make it public

2024-09-27 09:14 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Once you find a bug, want to discuss something, or propose a new enhancement, please follow this GitHub feedback https://www.github.com/discussion#blabla[discussion] link.
```suggestion
If you find a bug, want to discuss something, or propose a new enhancement, please follow this GitHub feedback https://www.github.com/discussion#blabla[discussion] link.
```

2024-11-14 09:03 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +It would be good to mention a few drawbacks, that stand out when working with the current https://github.com/keycloak/keycloak/tree/main/testsuite[test suite]. First of all, is the complexity of vari
Not convinced about the statement `the massive amount of tests without knowledge if they are needed anymore`. There may be some tests not needed, but probably not a massive amount. Perhaps just drop this?

2024-11-14 09:04 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +The Keycloak team began an effort to design a new test framework in May 2024. It started with a prototype to verify if our ideas were feasible. The prototype was based on the https://junit.org/junit5
```suggestion
The Keycloak team began an effort to design a new test framework in May 2024. It started with a prototype to verify if our ideas were feasible. The prototype was based on the https://junit.org/junit5/[_JUnit5_ testing framework], specifically to implement https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks[_JUnit5_ callback classes] which extend the default test lifecycle functionality and provide custom inject annotations, like _@KeycloakIntegrationTest_, _@InjectWebDriver_ or _@InjectRealm_.
```

Perhaps writing something like `The prototype is an JUnit 5 Extension...`

2024-11-14 09:05 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +----
Would drop this, folks just need to know it's a JUnit 5 extension that is automatically added when you add the dependency; they don't need to know the internals.

2024-11-14 09:06 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +After a successful test round, we've continued with a proof of concept extending features list to support multiple server modes, different databases and _WebDrivers_, clients and users setup, _SmallR
The full list of features in the annotations package isn't the best way to list the features; and now that we split it up into multiple modules it doesn't list all annotations.

2024-11-14 09:08 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +After a successful test round, we've continued with a proof of concept extending features list to support multiple server modes, different databases and _WebDrivers_, clients and users setup, _SmallR
Maybe just do a bullet point list of features?

2024-11-14 09:16 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +Main plan is to cover enough features for most functionalities currently available in the https://github.com/keycloak/keycloak/tree/main/testsuite[integration test suite]. Next future step shall be t
```suggestion
== Next steps

We already have enough capabilities in the new test framework to start migrating some tests from the old testsuite; and in fact already have our very first test migrated. We plan to migrate one package at a time from the old testsuite starting with `admin` tests, then moving on to `forms` and `oauth` packages. As we are doing this we will expand on the capabilities of the test framework.

Some features we know will be coming soon include:

* An easier way to deploy custom providers, not requiring a Maven build of the provider first
* Improved logging, making it easy to configure logging from tests as well as Keycloak
* Easy testing of OAuth and OpenID Connect, including a mock application
* Extension to allow running code on the tested server when it's not possible to easily test through only remote interfaces
```

We also have some more long term plans to deliver:

* Provider tests that can be used to easily test a provider by invoking the provider directly
* Parallel execution of tests, to take full advantage of multiple cores to reduce test execution time

2024-11-14 13:23 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +:title: "Writing new tests has never been easier than before." Keycloak Test Framework
This title won't show very nicely on the website or feeds

```suggestion
:title: Introducing the Keycloak Test Framework
```

2024-11-14 13:24 UTC, stianst commented on blog/2024/preview-keycloak-test-framework.adoc
> +:author: Lukas Hanusovsky, Stian Thorgersen
```suggestion
:author: Lukas Hanusovsky
```

2024-11-14 15:02 UTC, stianst approved these changes

2024-11-14 15:02 UTC, merged